"use client";

import { createContext, ReactNode, useContext, useEffect, useState } from "react";
import { Languages } from "lucide-react";
import { cn } from "./ui";

type Language = "en" | "mm";

const LanguageContext = createContext<{
  language: Language;
  setLanguage: (language: Language) => void;
}>({ language: "en", setLanguage: () => {} });

const MM: Record<string, string> = {
  "Dashboard": "ပင်မစာမျက်နှာ",
  "Sales & POS": "အရောင်းနှင့် POS",
  "Purchases": "အဝယ်",
  "Items": "ကုန်ပစ္စည်းများ",
  "Stock": "ကုန်လက်ကျန်",
  "3D Records": "3D မှတ်တမ်းများ",
  "Exchange": "ငွေလဲလှယ်",
  "Wallets": "ငွေစာရင်းများ",
  "Transfer": "ငွေလွှဲ",
  "Withdraw": "ငွေထုတ်",
  "Credit & Payable": "အကြွေးရရန်/ပေးရန်",
  "Income & Expense": "ဝင်ငွေ/ထွက်ငွေ",
  "Reports": "အစီရင်ခံစာ",
  "Customers": "ဖောက်သည်များ",
  "Suppliers": "ကုန်သွင်းသူများ",
  "Users & Roles": "အသုံးပြုသူနှင့် အခန်းကဏ္ဍ",
  "Settings": "ဆက်တင်များ",
  "Audit Logs": "စစ်ဆေးမှတ်တမ်း",
  "About Us": "ကျွန်ုပ်တို့အကြောင်း",
  "Repair Jobs": "ပြုပြင်ရေး မှတ်တမ်းများ",
  "Take in a device": "ဖုန်းလက်ခံမည်",
  "Mobile phone shop & repair": "ဖုန်းဆိုင်နှင့် ပြုပြင်ရေး",
  "Job": "အလုပ်နံပါတ်",
  "Device": "ဖုန်း",
  "Problem": "ချွတ်ယွင်းချက်",
  "Charge": "ဝန်ဆောင်ခ",
  "Brand": "အမှတ်တံဆိပ်",
  "Model": "မော်ဒယ်",
  "IMEI / serial": "IMEI / စက်နံပါတ်",
  "Came in with": "ပါလာသည့်ပစ္စည်း",
  "Estimated charge": "ခန့်မှန်း ဝန်ဆောင်ခ",
  "Deposit taken": "စရန်ငွေ",
  "Deposit went into": "စရန်ငွေ ဝင်သည့်စာရင်း",
  "Promised date": "ပြန်ပေးမည့်ရက်",
  "Final charge": "အပြီးသတ် ဝန်ဆောင်ခ",
  "Parts cost": "အပိုပစ္စည်းဖိုး",
  "Move to": "ပြောင်းမည်",
  "Balance paid into": "ကျန်ငွေ ဝင်သည့်စာရင်း",
  "To collect now": "ယခု ကောက်ရမည့်ငွေ",
  "Already paid (deposit)": "ပေးပြီး (စရန်)",
  "No repair jobs yet.": "ပြုပြင်ရေး မှတ်တမ်း မရှိသေးပါ။",
  "Repair job created": "ပြုပြင်ရေး မှတ်တမ်း ဖွင့်ပြီးပါပြီ",
  "Repair updated": "ပြုပြင်ရေး မှတ်တမ်း ပြင်ပြီးပါပြီ",
  "Handed back and paid": "ဖုန်းပြန်ပေးပြီး ငွေရှင်းပြီးပါပြီ",
  "All statuses": "အခြေအနေ အားလုံး",
  "Take it in": "လက်ခံမည်",
  "RECEIVED": "လက်ခံပြီး",
  "IN_PROGRESS": "ပြုပြင်နေဆဲ",
  "WAITING_PARTS": "ပစ္စည်းစောင့်ဆဲ",
  "DONE": "ပြီးစီး",
  "DELIVERED": "ပြန်ပေးပြီး",
  "Print slip": "ပြေစာ ထုတ်မည်",
  "New sale": "အရောင်းအသစ်",
  "Sale complete": "အရောင်း ပြီးပါပြီ",
  "What is Wallet Note?": "Wallet Note ဆိုတာ ဘာလဲ?",
  "Wallet Note keeps a small business's money, stock and records in one private workspace — on a phone, in Myanmar or English, without a shelf of notebooks.": "Wallet Note သည် လုပ်ငန်းငယ်တစ်ခုရဲ့ ငွေကြေး၊ ကုန်ပစ္စည်းနှင့် မှတ်တမ်းများကို သီးသန့်နေရာတစ်ခုတည်းမှာ စုစည်းပေးပါတယ် — ဖုန်းထဲမှာ၊ မြန်မာလို သို့မဟုတ် အင်္ဂလိပ်လိုနဲ့၊ စာအုပ်တွေ အများကြီး မလိုအပ်ဘဲ။",
  "Ready to start?": "စတင်ဖို့ အဆင်သင့်လား?",
  "Good to know": "သိထားသင့်သည်များ",
  "Money": "ငွေကြေး",
  "Every kyat in and out, across as many wallets as you keep.": "ငွေစာရင်း ဘယ်နှစ်ခုပဲရှိရှိ ဝင်ငွေထွက်ငွေ တစ်ကျပ်မကျန် မှတ်တမ်းတင်ပါ။",
  "Shop": "ဆိုင်",
  "For a counter that sells things.": "ပစ္စည်းရောင်းတဲ့ ကောင်တာအတွက်။",
  "2D & 3D": "2D နှင့် 3D",
  "The lottery book, kept without the paperwork.": "ထီစာအုပ်ကို စာရွက်စာတမ်း မရှုပ်ဘဲ ထိန်းသိမ်းပါ။",
  "Everything else": "အခြားအရာများ",
  "The parts that keep a business honest with itself.": "လုပ်ငန်းတစ်ခု ကိုယ့်ကိုယ်ကို ရိုးသားနေစေမယ့် အပိုင်းများ။",
  "Cash, KBZPay, bank — each with its own balance and history.": "ငွေသား၊ KBZPay၊ ဘဏ် — တစ်ခုချင်းစီ လက်ကျန်နှင့် မှတ်တမ်း သီးသန့်။",
  "Move money between wallets, with a fee if there is one.": "ငွေစာရင်းအချင်းချင်း လွှဲပြောင်းပါ၊ ဝန်ဆောင်ခ ရှိရင် ထည့်ပါ။",
  "Take money out and keep the reason with it.": "ငွေထုတ်ပြီး ဘာကြောင့်ထုတ်လဲဆိုတာ အတူမှတ်ထားပါ။",
  "Daily takings and costs under your own categories.": "နေ့စဉ် ဝင်ငွေနှင့် ကုန်ကျစရိတ်ကို ကိုယ်ပိုင်အမျိုးအစားများဖြင့် မှတ်ပါ။",
  "Who owes you, who you owe, and what has been settled.": "ဘယ်သူက ပေးရန်ရှိ၊ ဘယ်သူ့ကို ပေးရန်ရှိ၊ ဘယ်ဟာ ရှင်းပြီးပြီ။",
  "Buy and sell THB against MMK at your own rates, with the profit worked out.": "ကိုယ်ပိုင်နှုန်းထားဖြင့် ဘတ်ငွေ ဝယ်/ရောင်းပါ၊ အမြတ်ကို တွက်ပေးပါမည်။",
  "Ring up a sale by barcode or search, and take payment.": "ဘားကုဒ် သို့မဟုတ် ရှာဖွေ၍ ရောင်းပြီး ငွေလက်ခံပါ။",
  "Prices, cost, units and categories.": "စျေးနှုန်း၊ အရင်း၊ ယူနစ်နှင့် အမျိုးအစားများ။",
  "What is on the shelf, what moved, and what is running low.": "စင်ပေါ်မှာ ဘာကျန်၊ ဘာရွေ့သွား၊ ဘာနည်းလာပြီလဲ။",
  "What you bought in, from whom, and what is still owed.": "ဘာဝယ်ခဲ့၊ ဘယ်သူ့ဆီက၊ ဘယ်လောက် ပေးရန်ကျန်သေးလဲ။",
  "Daily sessions": "နေ့စဉ် အလှည့်များ",
  "Morning and evening open by themselves every trading day.": "ရောင်းဝယ်ရက်တိုင်း မနက်နှင့် ညနေ အလိုအလျောက် ပွင့်ပါသည်။",
  "Official results": "တရားဝင် ရလဒ်များ",
  "Numbers arrive on their own and settle the session against them.": "ဂဏန်းများ အလိုအလျောက် ရောက်လာပြီး အလှည့်ကို ရှင်းပေးပါသည်။",
  "Orders on Telegram": "Telegram မှ အော်ဒါများ",
  "Customers send numbers and a payment slip; you approve before anything is recorded.": "ဖောက်သည်က နံပါတ်နှင့် ငွေလွှဲပြေစာ ပို့ပါသည်။ သင် အတည်ပြုမှသာ မှတ်တမ်းတင်ပါသည်။",
  "Daily close, profit and loss, and export to a spreadsheet.": "နေ့ပိတ်စာရင်း၊ အမြတ်အရှုံးနှင့် spreadsheet အဖြစ် ထုတ်ယူခြင်း။",
  "Contacts, balances and history in one place.": "ဆက်သွယ်ရန်၊ လက်ကျန်နှင့် မှတ်တမ်း တစ်နေရာတည်းမှာ။",
  "Staff accounts that only reach what you allow.": "သင်ခွင့်ပြုထားသည့် အပိုင်းကိုသာ ရောက်နိုင်သော ဝန်ထမ်းအကောင့်များ။",
  "Who changed what, when — nothing is edited silently.": "ဘယ်သူက ဘာကို ဘယ်အချိန် ပြောင်းလဲ — တိတ်တဆိတ် ပြင်၍ မရပါ။",
  "Your workspace is yours": "သင့်နေရာသည် သင့်ဟာသာ",
  "Each business is separate. No other business can see your records.": "လုပ်ငန်းတစ်ခုချင်းစီ သီးခြားဖြစ်သည်။ အခြားလုပ်ငန်းများ သင့်မှတ်တမ်းကို မမြင်နိုင်ပါ။",
  "Only what you use": "သုံးတာကိုပဲ ပြသည်",
  "Pick your kind of business at sign-up and the rest stays out of the way.": "အကောင့်ဖွင့်စဉ် လုပ်ငန်းအမျိုးအစား ရွေးလိုက်ရုံဖြင့် မလိုအပ်တာများ ဖုံးထားပေးပါသည်။",
  "Myanmar or English": "မြန်မာ သို့မဟုတ် အင်္ဂလိပ်",
  "Switch language whenever you like.": "ဘာသာစကားကို အချိန်မရွေး ပြောင်းနိုင်ပါသည်။",
  "Works like an app": "App တစ်ခုလို အလုပ်လုပ်သည်",
  "Install it on a phone from the browser — no store needed.": "Browser ကနေ ဖုန်းထဲ တင်နိုင်ပါသည် — Store မလိုအပ်ပါ။",
  "Many branches, one picture": "ဆိုင်ခွဲများစွာ၊ ခြုံငုံမြင်ကွင်းတစ်ခု",
  "Keep branches apart, then see the whole business together.": "ဆိုင်ခွဲများကို သီးခြားထားပြီး လုပ်ငန်းတစ်ခုလုံးကိုလည်း စုပေါင်းကြည့်ပါ။",
  "Free to start": "အခမဲ့ စတင်နိုင်",
  "Create an account and begin. Nothing to pay up front.": "အကောင့်ဖွင့်ပြီး စတင်လိုက်ပါ။ ကြိုတင်ပေးချေစရာ မလိုပါ။",
  "Privacy": "ကိုယ်ရေးအချက်အလက်",
  "Delete account": "အကောင့်ဖျက်ရန်",
  "Sign in to your account": "သင့်အကောင့်သို့ ဝင်ရောက်ပါ",
  "Username or email": "အသုံးပြုသူအမည် သို့မဟုတ် အီးမေးလ်",
  "Username": "အသုံးပြုသူအမည်",
  "Password": "စကားဝှက်",
  "Sign in": "ဝင်မည်",
  "Signing in…": "ဝင်ရောက်နေသည်…",
  "New to Wallet Note?": "Wallet Note အသုံးပြုသူအသစ်လား?",
  "Create a free account": "အခမဲ့အကောင့်ဖွင့်မည်",
  "Create your Wallet Note": "သင့် Wallet Note ကိုဖန်တီးပါ",
  "Free private workspace for your business": "သင့်လုပ်ငန်းအတွက် အခမဲ့သီးသန့်နေရာ",
  "Business name": "လုပ်ငန်းအမည်",
  "Your name": "သင့်အမည်",
  "Phone": "ဖုန်း",
  "Main currency": "အဓိကငွေကြေး",
  "Email": "အီးမေးလ်",
  "Confirm password": "စကားဝှက်အတည်ပြု",
  "Use at least 8 characters.": "အနည်းဆုံး စာလုံး ၈ လုံးသုံးပါ။",
  "Create free account": "အခမဲ့အကောင့်ဖွင့်မည်",
  "Creating account...": "အကောင့်ဖန်တီးနေသည်...",
  "Already have an account?": "အကောင့်ရှိပြီးသားလား?",
  "Enable Mini Mart functions?": "Mini Mart လုပ်ဆောင်ချက်များ ဖွင့်မလား?",
  "Turn this on for items, stock, purchases, suppliers, and Sales & POS.": "ကုန်ပစ္စည်း၊ လက်ကျန်၊ အဝယ်၊ ကုန်သွင်းသူနှင့် POS အတွက် ဖွင့်ပါ။",
  "Wallet Note only": "Wallet Note သာ",
  "Enable Mini Mart": "Mini Mart ဖွင့်မည်",
  "Install App": "App ထည့်သွင်းမည်",
  "Install Wallet Note": "Wallet Note ထည့်သွင်းရန်",
  "Done": "ပြီးပြီ",
  "Toggle theme": "အရောင်ပုံစံပြောင်းရန်",
  "Sign out": "ထွက်မည်",
  "New transaction": "မှတ်တမ်းအသစ်",
  "Save": "သိမ်းမည်",
  "Saving…": "သိမ်းနေသည်…",
  "Save records": "မှတ်တမ်းများသိမ်းမည်",
  "Cancel": "မလုပ်တော့ပါ",
  "Close": "ပိတ်မည်",
  "Create": "ဖန်တီးမည်",
  "Update": "ပြင်ဆင်မည်",
  "Delete": "ဖျက်မည်",
  "Edit": "ပြင်မည်",
  "Add": "ထည့်မည်",
  "Search": "ရှာဖွေမည်",
  "Confirm": "အတည်ပြုမည်",
  "Submit": "တင်သွင်းမည်",
  "Reopen": "ပြန်ဖွင့်မည်",
  "Reverse": "ပြန်လှန်မည်",
  "Adjust": "ညှိနှိုင်းမည်",
  "View": "ကြည့်မည်",
  "Active": "အသုံးပြုနေ",
  "Inactive": "ပိတ်ထား",
  "OPEN": "ဖွင့်ထား",
  "CLOSED": "ပိတ်ပြီး",
  "SETTLED": "စာရင်းရှင်းပြီး",
  "PENDING": "စောင့်ဆိုင်း",
  "COMPLETED": "ပြီးစီး",
  "CANCELLED": "ပယ်ဖျက်ပြီး",
  "REVERSED": "ပြန်ရုပ်သိမ်းပြီး",
  "VOIDED": "ပယ်ဖျက်ပြီး",
  "WITHDRAW": "ငွေထုတ်",
  "CASH": "ငွေသား",
  "PAID": "ပေးချေပြီး",
  "UNPAID": "မပေးချေရသေး",
  "PARTIAL": "တစ်စိတ်တစ်ပိုင်း",
  "INCOME": "ဝင်ငွေ",
  "EXPENSE": "ထွက်ငွေ",
  "CUSTOMER": "ဖောက်သည်",
  "SUPPLIER": "ကုန်သွင်းသူ",
  "Name": "အမည်",
  "Full name": "အမည်အပြည့်အစုံ",
  "Code": "ကုဒ်",
  "Type": "အမျိုးအစား",
  "Currency": "ငွေကြေး",
  "Branch": "ဆိုင်ခွဲ",
  "Role": "အခန်းကဏ္ဍ",
  "Status": "အခြေအနေ",
  "Actions": "လုပ်ဆောင်ချက်များ",
  "Date": "ရက်စွဲ",
  "From": "မှ",
  "To": "အထိ",
  "Amount": "ငွေပမာဏ",
  "Quantity": "အရေအတွက်",
  "Price": "ဈေးနှုန်း",
  "Total": "စုစုပေါင်း",
  "Balance": "လက်ကျန်",
  "Profit": "အမြတ်",
  "Payment": "ပေးချေမှု",
  "Payment status": "ပေးချေမှုအခြေအနေ",
  "Transaction": "ငွေလွှဲမှတ်တမ်း",
  "Transactions": "ငွေလွှဲမှတ်တမ်းများ",
  "Fee": "ဝန်ဆောင်ခ",
  "Notes": "မှတ်ချက်",
  "Description": "ဖော်ပြချက်",
  "Reference": "ရည်ညွှန်းချက်",
  "Address": "လိပ်စာ",
  "Telegram": "တယ်လီဂရမ်",
  "Website": "ဝဘ်ဆိုက်",
  "Category": "အမျိုးအစား",
  "Unit": "ယူနစ်",
  "Barcode": "ဘားကုဒ်",
  "Reason (required)": "အကြောင်းပြချက် (မဖြစ်မနေ)",
  "Due date": "ပေးချေရမည့်ရက်",
  "Opening balance": "အစလက်ကျန်",
  "Current balance": "လက်ရှိလက်ကျန်",
  "Minimum balance alert": "အနည်းဆုံးလက်ကျန် သတိပေးချက်",
  "From wallet": "ထွက်မည့်ငွေစာရင်း",
  "To wallet": "ဝင်မည့်ငွေစာရင်း",
  "Cash wallet": "ငွေသားစာရင်း",
  "Txn": "မှတ်တမ်းနံပါတ်",
  "Reason": "အကြောင်းပြချက်",
  "Reason / note": "အကြောင်းပြချက် / မှတ်ချက်",
  "Void": "ပယ်ဖျက်",
  "Saving...": "သိမ်းဆည်းနေသည်...",
  "Money Transfer": "ငွေလွှဲပြောင်းခြင်း",
  "New transfer": "ငွေလွှဲအသစ်",
  "Reverse transfer": "ငွေလွှဲကို ပြန်ရုပ်သိမ်းရန်",
  "Confirm transfer": "ငွေလွှဲရန် အတည်ပြုမည်",
  "Transferring...": "ငွေလွှဲနေသည်...",
  "Transfer completed": "ငွေလွှဲပြီးပါပြီ",
  "Transfer failed": "ငွေလွှဲ၍ မရပါ",
  "Transfer reversed": "ငွေလွှဲကို ပြန်ရုပ်သိမ်းပြီးပါပြီ",
  "Reverse failed": "ပြန်ရုပ်သိမ်း၍ မရပါ",
  "No transfers yet": "ငွေလွှဲမှတ်တမ်း မရှိသေးပါ",
  "New withdrawal": "ငွေထုတ်အသစ်",
  "Void withdrawal": "ငွေထုတ်ကို ပယ်ဖျက်ရန်",
  "Confirm withdrawal": "ငွေထုတ်ရန် အတည်ပြုမည်",
  "Withdrawal recorded": "ငွေထုတ် မှတ်တမ်းတင်ပြီးပါပြီ",
  "Withdrawal failed": "ငွေထုတ်၍ မရပါ",
  "Withdrawal voided": "ငွေထုတ်ကို ပယ်ဖျက်ပြီးပါပြီ",
  "Void failed": "ပယ်ဖျက်၍ မရပါ",
  "No withdrawals yet": "ငွေထုတ်မှတ်တမ်း မရှိသေးပါ",
  "Direction": "ငွေဝင်/ထွက်",
  "Wallet": "ငွေစာရင်း",
  "New wallet": "ငွေစာရင်းအသစ်",
  "Wallet transfer": "ငွေစာရင်းအချင်းချင်းလွှဲရန်",
  "New user": "အသုံးပြုသူအသစ်",
  "New custom role": "အခန်းကဏ္ဍအသစ်",
  "Role name": "အခန်းကဏ္ဍအမည်",
  "New supplier": "ကုန်သွင်းသူအသစ်",
  "New contact": "အဆက်အသွယ်အသစ်",
  "New item": "ကုန်ပစ္စည်းအသစ်",
  "Categories & Units": "အမျိုးအစားနှင့် ယူနစ်",
  "Cost price": "ဝယ်ဈေး",
  "Selling price": "ရောင်းဈေး",
  "Min stock": "အနည်းဆုံးလက်ကျန်",
  "New purchase": "အဝယ်အသစ်",
  "Supplier": "ကုန်သွင်းသူ",
  "Discount": "လျှော့ဈေး",
  "Paid now": "ယခုပေးချေငွေ",
  "Pay from wallet": "ပေးချေမည့်ငွေစာရင်း",
  "New income / expense": "ဝင်ငွေ/ထွက်ငွေ အသစ်",
  "New exchange transaction": "ငွေလဲလှယ်မှုအသစ်",
  "Service fee (MMK)": "ဝန်ဆောင်ခ (MMK)",
  "3D Sessions": "3D အကြိမ်များ",
  "New session": "အကြိမ်အသစ်",
  "Export / Import": "Export / Import",
  "3D records export / import": "3D မှတ်တမ်း Export / Import",
  "Export selected session": "ရွေးထားသောအကြိမ်ကို Export လုပ်မည်",
  "Download import template": "Import Template ယူမည်",
  "Import branch": "Import ထည့်မည့်ဆိုင်ခွဲ",
  "Completed template CSV": "ဖြည့်ပြီးသော Template CSV",
  "Download the import template first.": "Import Template ကို အရင်ယူပါ။",
  "Importing...": "Import လုပ်နေသည်...",
  "New 3D session": "3D အကြိမ်အသစ်",
  "Session": "အကြိမ်",
  "Session name": "အကြိမ်အမည်",
  "Draw date": "ထွက်မည့်ရက်",
  "Draw time": "ထွက်မည့်အချိန်",
  "Cut-off time": "ပိတ်မည့်အချိန်",
  "Default odds (payout multiplier)": "မူလအလျော်",
  "Result": "ထွက်ဂဏန်း",
  "Records": "မှတ်တမ်းများ",
  "Total bet": "စုစုပေါင်းထိုးငွေ",
  "Exposure": "ပေးလျော်နိုင်ခြေ",
  "Official 3D result history": "တရားဝင် 3D ထွက်ဂဏန်းမှတ်တမ်း",
  "Official result history is waiting for the API provider.": "API မှ ထွက်ဂဏန်းမှတ်တမ်းကို စောင့်ဆိုင်းနေသည်။",
  "Official": "တရားဝင်",
  "Time": "အချိန်",
  "Morning": "မနက်ပိုင်း",
  "Evening": "ညနေပိုင်း",
  "New records": "မှတ်တမ်းအသစ်",
  "New 3D records": "3D မှတ်တမ်းအသစ်",
  "Customer name (optional)": "ဖောက်သည်အမည် (မထည့်လည်းရ)",
  "Phone (optional)": "ဖုန်း (မထည့်လည်းရ)",
  "Commission % (optional)": "ကော်မရှင် % (မထည့်လည်းရ)",
  "Enter result & settle": "ထွက်ဂဏန်းထည့်ပြီး စာရင်းရှင်းမည်",
  "Winning number (3 digits)": "ပေါက်ဂဏန်း (၃ လုံး)",
  "Preview settlement": "စာရင်းရှင်းမှုကြိုကြည့်မည်",
  "Reopen settlement": "စာရင်းရှင်းမှု ပြန်ဖွင့်မည်",
  "Close session": "အကြိမ်ပိတ်မည်",
  "Reopen entry": "ထိုးစာရင်းပြန်ဖွင့်မည်",
  "Total commission": "စုစုပေါင်းကော်မရှင်",
  "Potential payout": "ပေးလျော်နိုင်သည့်ငွေ",
  "Settlement result": "စာရင်းရှင်းရလဒ်",
  "Gross collected": "စုစုပေါင်းရငွေ",
  "Winning payout": "ပေါက်ဂဏန်းပေးလျော်ငွေ",
  "Net profit/loss": "အသားတင်အမြတ်/အရှုံး",
  "Customer": "ဖောက်သည်",
  "Customers owe us": "ဖောက်သည်ထံမှ ရရန်",
  "We owe suppliers": "ကုန်သွင်းသူသို့ ပေးရန်",
  "Total income": "စုစုပေါင်းဝင်ငွေ",
  "Total expense": "စုစုပေါင်းထွက်ငွေ",
  "Total sales": "စုစုပေါင်းအရောင်း",
  "Total profit": "စုစုပေါင်းအမြတ်",
  "Today's Sales": "ယနေ့အရောင်း",
  "Sales Profit": "အရောင်းအမြတ်",
  "Total MMK Balance": "MMK စုစုပေါင်းလက်ကျန်",
  "Total THB Balance": "THB စုစုပေါင်းလက်ကျန်",
  "Customer Receivable": "ဖောက်သည်ထံမှ ရရန်",
  "Business Payable": "လုပ်ငန်းမှ ပေးရန်",
  "Today's Income": "ယနေ့ဝင်ငွေ",
  "Today's Expense": "ယနေ့ထွက်ငွေ",
  "Net Cash Movement": "အသားတင်ငွေ အဝင်/အထွက်",
  "No records yet": "မှတ်တမ်းမရှိသေးပါ",
  "No wallets yet": "ငွေစာရင်းမရှိသေးပါ",
  "No items found": "ကုန်ပစ္စည်းမတွေ့ပါ",
  "No customers found": "ဖောက်သည်မတွေ့ပါ",
  "No suppliers found": "ကုန်သွင်းသူမတွေ့ပါ",
  "No transactions found": "ငွေလွှဲမှတ်တမ်းမတွေ့ပါ",
  "No sessions yet. Create the first draw session.": "3D အကြိမ်မရှိသေးပါ။ ပထမအကြိမ်ဖန်တီးပါ။",
  "Search name or phone…": "အမည် သို့မဟုတ် ဖုန်းဖြင့်ရှာရန်…",
  "Search supplier name or phone...": "ကုန်သွင်းသူအမည် သို့မဟုတ် ဖုန်းဖြင့်ရှာရန်…",
  "Search name, SKU, or barcode…": "အမည်၊ SKU သို့မဟုတ် ဘားကုဒ်ဖြင့်ရှာရန်…",
  "Search or scan barcode…": "ရှာရန် သို့မဟုတ် ဘားကုဒ်ဖတ်ရန်…",
  "3D Settled P/L": "3D စာရင်းရှင်း အမြတ်/အရှုံး",
  "3D Total Today": "ယနေ့ 3D စုစုပေါင်း",
  "3D commission %": "3D ကော်မရှင် %",
  "3D profit": "3D အမြတ်",
  "3D records": "3D မှတ်တမ်းများ",
  "3D settings": "3D ဆက်တင်များ",
  "3D volume": "3D ထိုးငွေပမာဏ",
  "Actual counted balance": "အမှန်တကယ်ရေတွက်ထားသောလက်ကျန်",
  "Add money (debit)": "ငွေထည့်မည်",
  "Adjust balance": "လက်ကျန်ညှိမည်",
  "Adjustment (+ to add, − to remove)": "ညှိမည့်ပမာဏ (+ ထည့်၊ − နုတ်)",
  "All branches": "ဆိုင်ခွဲအားလုံး",
  "All modules": "လုပ်ဆောင်ချက်အားလုံး",
  "All types": "အမျိုးအစားအားလုံး",
  "Amount received now": "ယခုရရှိငွေ",
  "App name": "App အမည်",
  "Auto refresh: 30 seconds": "စက္ကန့် ၃၀ တိုင်း အလိုအလျောက်ပြန်တင်မည်",
  "Branches": "ဆိုင်ခွဲများ",
  "Business profile": "လုပ်ငန်းအချက်အလက်",
  "Buy THB (pay MMK)": "THB ဝယ်မည် (MMK ပေး)",
  "Buy rate (we buy THB at)": "THB ဝယ်ဈေး",
  "Cancel purchase": "အဝယ်ပယ်ဖျက်မည်",
  "Cancel sale": "အရောင်းပယ်ဖျက်မည်",
  "Categories": "အမျိုးအစားများ",
  "Close a day": "တစ်နေ့တာပိတ်မည်",
  "Closing notes": "ပိတ်သိမ်းမှတ်ချက်",
  "Collected:": "ကောက်ခံရငွေ:",
  "Commission:": "ကော်မရှင်:",
  "Contact phone": "ဆက်သွယ်ရန်ဖုန်း",
  "Copyright": "မူပိုင်ခွင့်",
  "Create role": "အခန်းကဏ္ဍဖန်တီးမည်",
  "Create user": "အသုံးပြုသူဖန်တီးမည်",
  "Credit Collected Today": "ယနေ့အကြွေးကောက်ခံရငွေ",
  "Credit history": "အကြွေးမှတ်တမ်း",
  "Credit limit": "အကြွေးကန့်သတ်ချက်",
  "Current payable": "လက်ရှိပေးရန်",
  "Current receivable": "လက်ရှိရရန်",
  "Customers & Contacts": "ဖောက်သည်နှင့် အဆက်အသွယ်များ",
  "Daily Close": "နေ့စဉ်စာရင်းပိတ်",
  "Daily breakdown": "နေ့စဉ်အသေးစိတ်",
  "Daily income vs expense": "နေ့စဉ်ဝင်ငွေနှင့် ထွက်ငွေ",
  "Default commission %": "မူလကော်မရှင် %",
  "Default odds": "မူလအလျော်",
  "Developer": "ဖန်တီးသူ",
  "Developer / company": "ဖန်တီးသူ / ကုမ္ပဏီ",
  "Due date (unpaid part)": "ကျန်ငွေပေးချေရမည့်ရက်",
  "Exchange Buy (THB)": "THB ဝယ်ယူမှု",
  "Exchange Profit": "ငွေလဲအမြတ်",
  "Exchange Sell (THB)": "THB ရောင်းချမှု",
  "Exchange history": "ငွေလဲမှတ်တမ်း",
  "Exchange profit": "ငွေလဲအမြတ်",
  "Exchange records": "ငွေလဲမှတ်တမ်းများ",
  "Expense": "ထွက်ငွေ",
  "Expense category": "ထွက်ငွေအမျိုးအစား",
  "Export data (CSV)": "ဒေတာထုတ်ယူမည် (CSV)",
  "Exposure by number (highest first)": "ဂဏန်းအလိုက်ပေးလျော်နိုင်ခြေ (အများဆုံးမှ)",
  "Gross collected:": "စုစုပေါင်းရငွေ:",
  "History": "မှတ်တမ်း",
  "Income": "ဝင်ငွေ",
  "Income − Expense": "ဝင်ငွေ − ထွက်ငွေ",
  "Leading zeros are preserved: 001, 010 and 100 are different numbers.": "ရှေ့ဆုံးသုညကို ထိန်းထားမည်။ 001၊ 010 နှင့် 100 သည် မတူညီသောဂဏန်းများဖြစ်သည်။",
  "Lines": "စာရင်းကြောင်းများ",
  "Low stock alerts": "ကုန်လက်ကျန်နည်း သတိပေးချက်",
  "Low wallet balance alerts": "ငွေလက်ကျန်နည်း သတိပေးချက်",
  "Max amount per number": "ဂဏန်းတစ်လုံးအများဆုံးထိုးငွေ",
  "Mini Mart functions": "Mini Mart လုပ်ဆောင်ချက်များ",
  "Money Exchange": "ငွေလဲလှယ်",
  "Net movement:": "အသားတင်အဝင်/အထွက်:",
  "Net profit / loss": "အသားတင်အမြတ် / အရှုံး",
  "New entry": "မှတ်တမ်းအသစ်",
  "New exchange": "ငွေလဲအသစ်",
  "New role": "အခန်းကဏ္ဍအသစ်",
  "Next": "နောက်သို့",
  "No pending sessions": "စောင့်ဆိုင်းနေသောအကြိမ်မရှိပါ",
  "No wallet movement": "ငွေစာရင်းမရွှေ့ပါ",
  "Numbers — one per line as number=amount": "ဂဏန်းများ — တစ်ကြောင်းလျှင် ဂဏန်း=ငွေပမာဏ",
  "Open POS": "POS ဖွင့်မည်",
  "Original": "မူရင်း",
  "Other": "အခြား",
  "Paid": "ပေးချေပြီး",
  "Payable Paid Today": "ယနေ့ပေးရန် ပေးချေပြီး",
  "Pending 3D sessions": "စောင့်ဆိုင်းနေသော 3D အကြိမ်များ",
  "Preview summary": "အနှစ်ချုပ်ကြိုကြည့်မည်",
  "Previous": "နောက်သို့ပြန်",
  "Print": "ပုံနှိပ်မည်",
  "Profit:": "အမြတ်:",
  "Rate (MMK per 1 THB)": "နှုန်း (THB ၁ ဘတ်လျှင် MMK)",
  "Receive into wallet": "လက်ခံမည့်ငွေစာရင်း",
  "Recent 3D records": "လတ်တလော 3D မှတ်တမ်းများ",
  "Recent exchanges": "လတ်တလောငွေလဲမှတ်တမ်း",
  "Records:": "မှတ်တမ်းများ:",
  "Registration and user activity": "အကောင့်ဖွင့်မှုနှင့် အသုံးပြုမှု",
  "Remaining": "ကျန်ငွေ",
  "Remove money (credit)": "ငွေနုတ်မည်",
  "Reopen day": "နေ့စဉ်စာရင်းပြန်ဖွင့်မည်",
  "Reverse exchange transaction": "ငွေလဲမှတ်တမ်းပြန်လှန်မည်",
  "Sales": "အရောင်း",
  "Save changes": "ပြင်ဆင်ချက်များသိမ်းမည်",
  "Save profile": "လုပ်ငန်းအချက်အလက်သိမ်းမည်",
  "Save rate": "နှုန်းသိမ်းမည်",
  "Save reconciliation": "စာရင်းတိုက်မှုသိမ်းမည်",
  "Select customer…": "ဖောက်သည်ရွေးပါ…",
  "Select item…": "ကုန်ပစ္စည်းရွေးပါ…",
  "Select wallet…": "ငွေစာရင်းရွေးပါ…",
  "Select…": "ရွေးချယ်ပါ…",
  "Sell THB (receive MMK)": "THB ရောင်းမည် (MMK လက်ခံ)",
  "Sell rate (we sell THB at)": "THB ရောင်းဈေး",
  "Settlement wallet (optional — records net P/L movement)": "စာရင်းရှင်းမည့်ငွေစာရင်း (မထည့်လည်းရ)",
  "Subtotal": "စုစုပေါင်းခွဲ",
  "System balance:": "စနစ်လက်ကျန်:",
  "Tap items to add them": "ထည့်လိုသောကုန်ပစ္စည်းကို နှိပ်ပါ",
  "The unpaid amount becomes a customer credit record.": "မပေးချေရသေးသောငွေကို ဖောက်သည်အကြွေးအဖြစ် မှတ်တမ်းတင်မည်။",
  "Unit cost": "တစ်ယူနစ်ဝယ်ဈေး",
  "Units": "ယူနစ်များ",
  "Unsettled 3D": "မရှင်းရသေးသော 3D",
  "Update THB/MMK board rate": "THB/MMK နှုန်းပြင်မည်",
  "Update rate": "နှုန်းပြင်မည်",
  "Version": "ဗားရှင်း",
  "WIN": "ပေါက်",
  "Wallets & cash": "ငွေစာရင်းနှင့် ငွေသား",
  "Warning threshold": "သတိပေးမည့်ပမာဏ",
  "We buy THB @": "THB ဝယ်ဈေး @",
  "We sell THB @": "THB ရောင်းဈေး @",
  "Winning payout:": "ပေါက်ဂဏန်းပေးလျော်ငွေ:",
  "Winning records": "ပေါက်သောမှတ်တမ်းများ",
  "Both wallet movements will be reversed. This action is logged.": "ငွေစာရင်းနှစ်ဖက်စလုံးကို ပြန်လှန်မည်။ ဤလုပ်ဆောင်ချက်ကို မှတ်တမ်းတင်ထားမည်။",
  "Changing the board rate never modifies existing transactions. Full history is kept.": "နှုန်းပြောင်းခြင်းသည် မှတ်တမ်းဟောင်းများကို မပြောင်းပါ။ နှုန်းမှတ်တမ်းအားလုံး သိမ်းထားမည်။",
  "Reopening allows transactions to be edited for this date again. The action is logged.": "ပြန်ဖွင့်ပြီးနောက် ဤရက်စွဲ၏မှတ်တမ်းများကို ပြန်ပြင်နိုင်မည်။ လုပ်ဆောင်ချက်ကို မှတ်တမ်းတင်ထားမည်။",
  "Stock and wallet payment are reversed. Logged in the audit trail.": "ကုန်လက်ကျန်နှင့် ငွေပေးချေမှုကို ပြန်လှန်ပြီး စစ်ဆေးမှတ်တမ်းတွင် သိမ်းထားမည်။",
  "Action": "လုပ်ဆောင်ချက်",
  "Module": "အပိုင်း",
  "Resource": "အရာ",
  "User": "အသုံးပြုသူ",
  "Item": "ပစ္စည်း",
  "Number": "နံပါတ်",
  "Bet": "ထိုးကြေး",
  "Bets": "ထိုးကြေးအရေအတွက်",
  "Odds": "အလျော်",
  "Payout": "အလျော်ငွေ",
  "Qty": "အရေအတွက်",
  "Cost": "ဝယ်ဈေး",
  "Rate": "နှုန်း",
  "Change": "အကြွေ",
  "Received": "လက်ခံငွေ",
  "Remove": "ဖယ်ရှားမည်",
  "Back": "နောက်သို့",
  "Clear": "ရှင်းမည်",
  "Send": "ပို့မည်",
  "Refresh": "ပြန်ဆွဲမည်",
  "Today": "ယနေ့",
  "Full": "အပြည့်",
  "Due": "ပေးရန်",
  "Out": "ထွက်",
  "After": "ပြီးနောက်",
  "Min": "အနည်းဆုံး",
  "Aging": "သက်တမ်း",
  "Draw": "ထီအလှည့်",
  "Value": "တန်ဖိုး",
  "Line": "စာကြောင်း",
  "Why": "အကြောင်းရင်း",
  "What": "ဘာလုပ်သည်",
  "Content": "အကြောင်းအရာ",
  "Product": "ကုန်ပစ္စည်း",
  "Commission": "ကော်မရှင်",
  "Business": "လုပ်ငန်း",
  "Account": "အကောင့်",
  "Registered": "မှတ်ပုံတင်ချိန်",
  "Choose…": "ရွေးပါ…",
  "Choose one…": "တစ်ခု ရွေးပါ…",
  "Choose category...": "အမျိုးအစား ရွေးပါ...",
  "Select customer...": "ဖောက်သည် ရွေးပါ...",
  "All categories": "အမျိုးအစား အားလုံး",
  "All actions": "လုပ်ဆောင်ချက် အားလုံး",
  "All users": "အသုံးပြုသူ အားလုံး",
  "All billers": "Biller အားလုံး",
  "Review sale": "အရောင်း ပြန်စစ်ရန်",
  "Cash received (optional)": "လက်ခံငွေ (ရွေးချယ်နိုင်)",
  "Cash received is less than the total.": "လက်ခံငွေက စုစုပေါင်းထက် နည်းနေပါတယ်။",
  "Discount cannot exceed subtotal.": "လျှော့ဈေးက စုစုပေါင်းထက် များလို့ မရပါ။",
  "Customer owes": "ဖောက်သည် ပေးရန်",
  "The unpaid amount is money the customer owes your business.": "မပေးရသေးတဲ့ ပမာဏက ဖောက်သည်ဆီက ပြန်ကောက်ရမယ့် ငွေပါ။",
  "Increase quantity": "အရေအတွက် တိုးမည်",
  "Decrease quantity": "အရေအတွက် လျှော့မည်",
  "Search or scan barcode...": "ရှာရန် သို့မဟုတ် barcode scan ဖတ်ရန်...",
  "Scan with the camera": "ကင်မရာနဲ့ ဖတ်မည်",
  "Scan items into the sale": "ပစ္စည်းများကို scan ဖတ်ထည့်မည်",
  "Print to roll printer (RawBT)": "စက္ကူလိပ် printer နဲ့ ထုတ်မည် (RawBT)",
  "Owing": "ကျန်ငွေ",
  "Thank you": "ကျေးဇူးတင်ပါသည်",
  "Import CSV": "CSV မှ သွင်းမည်",
  "Import products from a CSV": "CSV မှ ကုန်ပစ္စည်းများ သွင်းမည်",
  "Template": "နမူနာဖိုင်",
  "Choose another file": "တခြားဖိုင် ရွေးမည်",
  "What will be saved": "သိမ်းမည့် စာရင်း",
  "Rows that will be skipped": "ကျော်သွားမည့် စာကြောင်းများ",
  "Stock value (cost)": "လက်ကျန်တန်ဖိုး (ဝယ်ဈေး)",
  "Stock Value (cost)": "လက်ကျန်တန်ဖိုး (ဝယ်ဈေး)",
  "Stock Value (retail)": "လက်ကျန်တန်ဖိုး (ရောင်းဈေး)",
  "No items": "ပစ္စည်း မရှိပါ",
  "No movements": "ရွေ့လျားမှု မရှိပါ",
  "No purchases yet": "အဝယ် မရှိသေးပါ",
  "Add line": "စာကြောင်း ထပ်ထည့်",
  "Add one first": "အရင် တစ်ခု ထည့်ပါ",
  "No sales yet — open the POS to make the first sale": "အရောင်း မရှိသေးပါ — POS ဖွင့်ပြီး ပထမဆုံး အရောင်း စတင်ပါ",
  "Top-up Billers": "ဖုန်းဖြည့် Biller များ",
  "New biller": "Biller အသစ်",
  "Biller": "Biller",
  "Top-up card": "ဖြည့်သွင်းကတ်",
  "E-load": "E-load",
  "Sell": "ရောင်းမည်",
  "Buy float": "လက်ကျန် ဝယ်မည်",
  "Float after": "ပြီးနောက် လက်ကျန်",
  "Float held now": "လက်ရှိ လက်ကျန်",
  "Float held with all operators": "Operator အားလုံးမှာ ရှိတဲ့ လက်ကျန်",
  "Margin": "အမြတ်",
  "Margin on this trade": "ဤအရောင်းအဝယ်၏ အမြတ်",
  "Face": "မျက်နှာဖုံးတန်ဖိုး",
  "Recent movements": "မကြာသေးမီ ရွေ့လျားမှုများ",
  "Nothing recorded yet.": "မှတ်တမ်း မရှိသေးပါ။",
  "No billers yet. Add the operators this shop buys float from.": "Biller မရှိသေးပါ။ ဤဆိုင်က လက်ကျန်ဝယ်တဲ့ operator များကို ထည့်ပါ။",
  "Customer phone": "ဖောက်သည် ဖုန်း",
  "Money on each number": "နံပါတ်တစ်ခုချင်းစီ၏ ငွေပမာဏ",
  "Over the limit, in total": "ကန့်သတ်ချက် ကျော်လွန်မှု စုစုပေါင်း",
  "No records on this draw yet.": "ဤအလှည့်တွင် မှတ်တမ်း မရှိသေးပါ။",
  "Pass on": "လွှဲမည်",
  "Limit per number": "နံပါတ်တစ်ခုစီ ကန့်သတ်ချက်",
  "Limit (MMK)": "ကန့်သတ်ချက် (ကျပ်)",
  "Leave it empty for no limit.": "ကန့်သတ်ချက် မလိုရင် ကွက်လပ် ချန်ထားပါ။",
  "Amount to pass on": "လွှဲမည့် ပမာဏ",
  "Their odds": "သူတို့၏ အလျော်နှုန်း",
  "Bookmaker": "ဒိုင်",
  "Who is taking it": "ဘယ်သူ လက်ခံမလဲ",
  "Back if it wins": "ပေါက်ရင် ပြန်ရမည်",
  "Passed to other bookmakers": "တခြားဒိုင်များသို့ လွှဲထားသည်",
  "Total stake": "စုစုပေါင်း ထိုးကြေး",
  "Payout if drawn": "ပေါက်ရင် အလျော်ငွေ",
  "Paid out": "လျော်ပြီး",
  "Add a missed session": "ကျန်ခဲ့သော အလှည့် ထည့်မည်",
  "Add a missed 2D session": "ကျန်ခဲ့သော 2D အလှည့် ထည့်မည်",
  "Official 2D result history": "တရားဝင် 2D ရလဒ် မှတ်တမ်း",
  "No official results fetched yet.": "တရားဝင် ရလဒ် မရသေးပါ။",
  "Morning — draws 12:01, closes 11:55": "မနက်ပိုင်း — ၁၂:၀၁ ထွက်၊ ၁၁:၅၅ ပိတ်",
  "Evening — draws 16:30, closes 16:25": "ညနေပိုင်း — ၁၆:၃၀ ထွက်၊ ၁၆:၂၅ ပိတ်",
  "Times and odds (85) are set from the draw you pick.": "အချိန်နှင့် အလျော် (၈၅) ကို ရွေးလိုက်တဲ့ အလှည့်အလိုက် သတ်မှတ်ပါတယ်။",
  "Set to the next official draw (the 1st or the 16th).": "နောက်လာမည့် တရားဝင် ထီအလှည့် (၁ ရက် သို့မဟုတ် ၁၆ ရက်) အတိုင်း သတ်မှတ်ထားသည်။",
  "2D Total Today": "ယနေ့ 2D စုစုပေါင်း",
  "2D Settled P/L": "2D ရှင်းပြီး အမြတ်/အရှုံး",
  "Unsettled 2D": "မရှင်းရသေးသော 2D",
  "Recent 2D records": "မကြာသေးမီ 2D မှတ်တမ်းများ",
  "No 2D records yet": "2D မှတ်တမ်း မရှိသေးပါ",
  "No 3D records": "3D မှတ်တမ်း မရှိပါ",
  "Customer gives": "ဖောက်သည် ပေးရမည်",
  "Customer receives": "ဖောက်သည် ရမည်",
  "Enter the amount and the rest is worked out at the rate above.": "ပမာဏ ထည့်လိုက်ရင် ကျန်တာကို အပေါ်က နှုန်းနဲ့ တွက်ပေးပါမယ်။",
  "No rate set yet. Type one, or set your board rate above.": "နှုန်း မသတ်မှတ်ရသေးပါ။ ရိုက်ထည့်ပါ သို့မဟုတ် အပေါ်မှာ ကိုယ်ပိုင်နှုန်း သတ်မှတ်ပါ။",
  "No exchange transactions yet": "ငွေလဲ မှတ်တမ်း မရှိသေးပါ",
  "No exchange records": "ငွေလဲ မှတ်တမ်း မရှိပါ",
  "Create one on the Wallets page": "ပိုက်ဆံအိတ် စာမျက်နှာမှာ တစ်ခု ဆောက်ပါ",
  "Minimum balance": "အနည်းဆုံး လက်ကျန်",
  "Delete wallet": "ပိုက်ဆံအိတ် ဖျက်မည်",
  "Reconcile": "စာရင်းတိုက်မည်",
  "No wallets": "ပိုက်ဆံအိတ် မရှိပါ",
  "No ledger entries": "စာရင်းမှတ်တမ်း မရှိပါ",
  "Void this record": "ဤမှတ်တမ်းကို ပယ်ဖျက်မည်",
  "Void entry": "မှတ်တမ်း ပယ်ဖျက်မည်",
  "Remove category": "အမျိုးအစား ဖယ်ရှားမည်",
  "New category name": "အမျိုးအစား အသစ်၏ အမည်",
  "Choose an existing category": "ရှိပြီးသား အမျိုးအစား ရွေးပါ",
  "No entries yet": "မှတ်တမ်း မရှိသေးပါ",
  "None yet.": "မရှိသေးပါ။",
  "No credit records": "အကြွေး မှတ်တမ်း မရှိပါ",
  "No contacts found": "အဆက်အသွယ် မတွေ့ပါ",
  "No audit entries": "စစ်ဆေးမှတ်တမ်း မရှိပါ",
  "No daily closes yet": "နေ့ပိတ်စာရင်း မရှိသေးပါ",
  "Reopen reason": "ပြန်ဖွင့်ရသည့် အကြောင်းရင်း",
  "The wallet movement will be reversed. This action is logged.": "ပိုက်ဆံအိတ် ရွေ့လျားမှုကို ပြန်လှန်ပါမည်။ ဤလုပ်ဆောင်ချက်ကို မှတ်တမ်းတင်ပါသည်။",
  "Customer name": "ဖောက်သည် အမည်",
  "Job no, customer, phone, brand, model or IMEI": "ဂျော့နံပါတ်၊ ဖောက်သည်၊ ဖုန်း၊ အမှတ်တံဆိပ်၊ မော်ဒယ် သို့မဟုတ် IMEI",
  "Write down what came with the device. It is the answer if anyone asks later.": "စက်နှင့်အတူ ပါလာသည့်အရာများကို ရေးမှတ်ပါ။ နောင် အငြင်းပွားလျှင် ဤစာက အဖြေဖြစ်ပါသည်။",
  "Accept bets from customers on Telegram": "Telegram မှ ဖောက်သည်များ၏ ထိုးကြေးများ လက်ခံမည်",
  "Off by default. Needs at least one payment method below.": "မူလအားဖြင့် ပိတ်ထားသည်။ အောက်တွင် ငွေပေးချေမှု နည်းလမ်း အနည်းဆုံး တစ်ခု လိုအပ်သည်။",
  "Add payment method": "ငွေပေးချေမှု နည်းလမ်း ထည့်မည်",
  "No payment methods yet.": "ငွေပေးချေမှု နည်းလမ်း မရှိသေးပါ။",
  "Account name": "အကောင့် အမည်",
  "Account number": "အကောင့် နံပါတ်",
  "Note (optional)": "မှတ်ချက် (ရွေးချယ်နိုင်)",
  "Show to customers": "ဖောက်သည်များကို ပြမည်",
  "Exchange rate": "ငွေလဲနှုန်း",
  "Follow the market rate": "ဈေးကွက်နှုန်းအတိုင်း လိုက်မည်",
  "Market today": "ယနေ့ ဈေးကွက်နှုန်း",
  "Buy adjustment (kyat)": "ဝယ်နှုန်း ချိန်ညှိ (ကျပ်)",
  "Sell adjustment (kyat)": "ရောင်းနှုန်း ချိန်ညှိ (ကျပ်)",
  "Save exchange settings": "ငွေလဲ ဆက်တင် သိမ်းမည်",
  "Save payment settings": "ငွေပေးချေမှု ဆက်တင် သိမ်းမည်",
  "Save 3D settings": "3D ဆက်တင် သိမ်းမည်",
  "Save sidebar functions": "ဘေးတန်း လုပ်ဆောင်ချက်များ သိမ်းမည်",
  "Sidebar functions": "ဘေးတန်း လုပ်ဆောင်ချက်များ",
  "Telegram orders & payment methods": "Telegram အော်ဒါနှင့် ငွေပေးချေမှု နည်းလမ်းများ",
  "Privacy and account": "ကိုယ်ရေးကိုယ်တာနှင့် အကောင့်",
  "Privacy policy": "ကိုယ်ရေးကိုယ်တာ မူဝါဒ",
  "Request account deletion": "အကောင့် ဖျက်ရန် တောင်းဆိုမည်",
  "Delete this business": "ဤလုပ်ငန်းကို ဖျက်မည်",
  "Access all branches": "ဌာနခွဲ အားလုံး ဝင်ခွင့်",
  "Bot token": "Bot token",
  "Disconnect bot": "Bot ဖြုတ်မည်",
  "Copy the token BotFather gives you and paste it below": "BotFather ပေးတဲ့ token ကို ကူးပြီး အောက်မှာ ကပ်ပါ",
  "Open Telegram and message": "Telegram ဖွင့်ပြီး စာပို့ပါ",
  "Open your bot in Telegram and send": "သင့် bot ကို Telegram မှာ ဖွင့်ပြီး ပို့ပါ",
  "What is this for?": "ဘာအတွက်လဲ?",
  "One question, so the app only shows what you use.": "မေးခွန်းတစ်ခုပါ — သုံးမယ့်အရာတွေပဲ ပြပေးဖို့ပါ။",
  "You can change any of this later in Settings.": "ဒါတွေအားလုံးကို နောက်မှ Settings မှာ ပြောင်းလို့ ရပါတယ်။",
  "Skip for now": "ယခုအတွက် ကျော်မည်",
  "Business category": "လုပ်ငန်း အမျိုးအစား",
  "Sign up with Google": "Google ဖြင့် အကောင့်ဖွင့်မည်",
  "Chosen for you from the link you followed. Change it if it is not right.": "သင် ဝင်လာတဲ့ link အရ ရွေးပေးထားပါတယ်။ မမှန်ရင် ပြောင်းပါ။",
  "MMK:": "ကျပ်:",
  "THB:": "ဘတ်:",
  "Buy THB:": "ဘတ် ဝယ်:",
  "Sell THB:": "ဘတ် ရောင်း:",
  "Paid:": "ပေးပြီး:",
  "Total:": "စုစုပေါင်း:",
  "Settled P/L:": "ရှင်းပြီး အမြတ်/အရှုံး:",
  "Income − Expense:": "ဝင်ငွေ − ထွက်ငွေ:",
  "Credit / Payable / General": "အကြွေး / ပေးရန် / အထွေထွေ",
  "Remaining:": "ကျန်ငွေ:",
  "Total outstanding:": "ပေးရန်ကျန် စုစုပေါင်း:",
  "The customer's payment will be added to this wallet. The wallet drop-down only lists wallets in the same currency.": "ဖောက်သည်၏ ငွေပေးချေမှုကို ဤပိုက်ဆံအိတ်ထဲ ထည့်ပါမည်။ တူညီသော ငွေကြေးရှိသည့် ပိုက်ဆံအိတ်များသာ ပေါ်ပါမည်။",
  "Note": "မှတ်ချက်",
  "Cash": "ငွေသား",
  "Numbers — one per line as number=amount, and a name after it if you want one": "နံပါတ်များ — တစ်ကြောင်းလျှင် နံပါတ်=ငွေပမာဏ၊ အမည် ထည့်လိုလျှင် နောက်မှာ ရေးပါ",
  "Past entries keep the category they were filed under, whatever happens here.": "အရင်မှတ်ထားသော မှတ်တမ်းများသည် သူတို့ မူလ အမျိုးအစားအတိုင်း ကျန်နေပါမည်။",
  "Stock returns to inventory and any wallet receipt is reversed. This is logged in the audit trail.": "ကုန်ပစ္စည်းများ လက်ကျန်ထဲ ပြန်ဝင်ပြီး ပိုက်ဆံအိတ် လက်ခံငွေကို ပြန်လှန်ပါမည်။ စစ်ဆေးမှတ်တမ်းတွင် သိမ်းထားပါမည်။",
  "The withdrawn amount will be returned to the wallet. This action is logged.": "ထုတ်ယူထားသော ပမာဏကို ပိုက်ဆံအိတ်ထဲ ပြန်ထည့်ပါမည်။ ဤလုပ်ဆောင်ချက်ကို မှတ်တမ်းတင်ပါသည်။",
  "Each person uses their": "လူတစ်ဦးချင်းစီသည် မိမိ၏",
  "Back to Wallet Note": "Wallet Note သို့ ပြန်သွားမည်",
  "Delete Wallet Note account": "Wallet Note အကောင့် ဖျက်မည်",
  "Registered email": "မှတ်ပုံတင်ထားသော အီးမေးလ်",
  "Owner username": "ပိုင်ရှင် အသုံးပြုသူအမည်",
  "Reason (optional)": "အကြောင်းရင်း (ရွေးချယ်နိုင်)",
  "Wallet Note Privacy Policy": "Wallet Note ကိုယ်ရေးကိုယ်တာ မူဝါဒ",
  "Who operates Wallet Note": "Wallet Note ကို ဘယ်သူ လည်ပတ်သလဲ",
  "Data we collect": "ကျွန်ုပ်တို့ စုဆောင်းသော အချက်အလက်",
  "How data is used and protected": "အချက်အလက်ကို မည်သို့ သုံးပြီး ကာကွယ်သလဲ",
  "Sharing and retention": "မျှဝေခြင်းနှင့် သိမ်းဆည်းခြင်း",
  "Your choices": "သင်၏ ရွေးချယ်ခွင့်များ",
  "Contact": "ဆက်သွယ်ရန်",
  "Grand Admin Portal": "Grand Admin Portal",
  "Enter the passcode to continue": "ဆက်လက်ရန် passcode ထည့်ပါ",
  "Passcode": "Passcode",
  "Wallet Note Admin": "Wallet Note စီမံခန့်ခွဲမှု",
  "Activity Audit Logs": "လုပ်ဆောင်ချက် စစ်ဆေးမှတ်တမ်းများ",
  "Show activity audit logs": "လုပ်ဆောင်ချက် မှတ်တမ်းများ ပြမည်",
  "Show all registered user details": "မှတ်ပုံတင်ထားသူ အားလုံး၏ အသေးစိတ် ပြမည်",
  "Show users registered today": "ယနေ့ မှတ်ပုံတင်သူများ ပြမည်",
  "No activity logs found.": "လုပ်ဆောင်ချက် မှတ်တမ်း မတွေ့ပါ။",
  "No registered users found.": "မှတ်ပုံတင်ထားသူ မတွေ့ပါ။",
  "Owner name": "ပိုင်ရှင် အမည်",
  "Login session": "ဝင်ရောက်မှု session",
  "Search username, business, module": "အသုံးပြုသူအမည်၊ လုပ်ငန်း၊ အပိုင်း ရှာရန်",
  "Search username, owner, business": "အသုံးပြုသူအမည်၊ ပိုင်ရှင်၊ လုပ်ငန်း ရှာရန်",
};

const originalText = new WeakMap<Node, string>();
const originalAttributes = new WeakMap<Element, Map<string, string>>();

function translate(value: string) {
  const trimmed = value.trim();
  const exact = MM[trimmed];
  if (exact) return value.replace(trimmed, exact);
  const patterns: Array<[RegExp, (...matches: string[]) => string]> = [
    [/^Edit (.+)$/, (name) => `${name} ကိုပြင်မည်`],
    [/^Adjust (.+)$/, (name) => `${name} လက်ကျန်ညှိမည်`],
    [/^Reconcile (.+)$/, (name) => `${name} စာရင်းတိုက်မည်`],
    [/^Cancel (.+)$/, (name) => `${name} ကိုပယ်ဖျက်မည်`],
    [/^Pay (.+)$/, (name) => `${name} ကိုပေးချေမည်`],
    [/^Odds \(default (.+)\)$/, (odds) => `အလျော် (မူလ ${odds})`],
    [/^Records \((\d+)\)$/, (count) => `မှတ်တမ်းများ (${count})`],
    [/^Amount \((.+)\)$/, (currency) => `ငွေပမာဏ (${currency})`],
    [/^Customer \(owes (.+)\)$/, (amount) => `ဖောက်သည် (ပေးရန် ${amount})`],
  ];
  for (const [pattern, formatter] of patterns) {
    const match = trimmed.match(pattern);
    if (match) return value.replace(trimmed, formatter(...match.slice(1)));
  }
  return value;
}

function applyLanguage(root: ParentNode, language: Language) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node: Node | null = walker.nextNode();
  while (node) {
    const current = node.nodeValue ?? "";
    const stored = originalText.get(node);
    if (!stored || (current !== stored && current !== translate(stored))) {
      originalText.set(node, current);
    }
    const original = originalText.get(node) ?? current;
    const next = language === "mm" ? translate(original) : original;
    if (current !== next) node.nodeValue = next;
    node = walker.nextNode();
  }

  const elements = root instanceof Element ? [root, ...root.querySelectorAll("*")] : [...root.querySelectorAll("*")];
  for (const element of elements) {
    for (const attribute of ["placeholder", "title", "aria-label"]) {
      const current = element.getAttribute(attribute);
      if (!current) continue;
      let stored = originalAttributes.get(element);
      if (!stored) {
        stored = new Map();
        originalAttributes.set(element, stored);
      }
      const original = stored.get(attribute);
      if (!original || (current !== original && current !== translate(original))) stored.set(attribute, current);
      const source = stored.get(attribute) ?? current;
      const next = language === "mm" ? translate(source) : source;
      if (current !== next) element.setAttribute(attribute, next);
    }
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("wn-language");
    const frame = window.requestAnimationFrame(() => {
      if (saved === "mm") setLanguageState("mm");
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === "mm" ? "my" : "en";
    applyLanguage(document.body, language);
    let frame = 0;
    const observer = new MutationObserver(() => {
      if (frame) return;
      frame = window.requestAnimationFrame(() => {
        frame = 0;
        applyLanguage(document.body, language);
      });
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    return () => {
      observer.disconnect();
      if (frame) window.cancelAnimationFrame(frame);
    };
  }, [language]);

  function setLanguage(next: Language) {
    localStorage.setItem("wn-language", next);
    setLanguageState(next);
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function LanguageSwitch({ className }: { className?: string }) {
  const { language, setLanguage } = useContext(LanguageContext);
  return (
    <div
      className={cn(
        "inline-flex h-10 items-center rounded-lg border border-gray-200 bg-gray-50 p-0.5 dark:border-gray-700 dark:bg-gray-800",
        className
      )}
      aria-label="Language"
    >
      <Languages size={16} className="mx-1.5 text-gray-500" />
      {(["mm", "en"] as const).map((item) => (
        <button
          key={item}
          type="button"
          onClick={() => setLanguage(item)}
          className={cn(
            "h-8 min-w-9 rounded-md px-2 text-xs font-semibold transition",
            language === item
              ? "bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-300"
              : "text-gray-500 dark:text-gray-400"
          )}
        >
          {item === "mm" ? "MM" : "EN"}
        </button>
      ))}
    </div>
  );
}
